# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20180625_2255'),
        ('trade', '0002_auto_20180613_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('paying', '待支付')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('user', 'goods')]),
        ),
    ]
